version: '3.8'
services:
    server:
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: server
        depends_on: [
            mongodb
        ]
        command: npm run start:watch
        ports: [ 
            "4000:4000" 
        ]
        volumes: [ 
            ./:/usr/app 
        ]
    mongodb:
        image: mongo:4.4.1-bionic
        container_name: mongodb
        ports: [
            27017:27017
        ]
        volumes: [
            ./db_m:/data/db
        ]
