import { Applicant} from '../../types/applicant';

const {google} = require('googleapis');

// this is path to json file with the service account keys
// these keys can be generated by creating a service account from the google developers console
// change the path to that of the file that you generate to access the sheets api
const keys = require('../../../keys.json');

const client = new google.auth.JWT(
  keys.client_email, null, keys.private_key, ['https://www.googleapis.com/auth/spreadsheets']
);

function authorize() {
    client.authorize(function (err) {
        if (err) {
            console.log(err);
        } else {
            console.log('Connected');
        }
    });
}

// note: if the sheets is not open to access by url, then need to make the service account email an editor
export async function getData(url: string, sheetName: string, range: string) {
    authorize();
    const gsapi = google.sheets({version: 'v4', auth: client});

    let id = url.match('/spreadsheets\\/d\\/([a-zA-Z0-9-_]+)')[0];
    id = id.replace('/spreadsheets/d/', '');

    const opt = {
        spreadsheetId: id,
        range: `${sheetName}!${range}`
    };

    let data = await gsapi.spreadsheets.values.get(opt);

    return data.data.values;
}


// note: if the sheets is not open to access by url, then need to make the service account email an editor
export async function addApplicant(url: string, sheetName: string, range: string, applicant: Applicant) {
    authorize();
    const gsapi = google.sheets({version: 'v4', auth: client});

    let id = url.match('/spreadsheets\\/d\\/([a-zA-Z0-9-_]+)')[0];
    id = id.replace('/spreadsheets/d/', '');

    const appendOptions = {
        spreadsheetId: id,
        range: `${sheetName}!${range}`,
        valueInputOption: 'USER_ENTERED',
        resource: {values: [
            [applicant.name, applicant.email, applicant.year, applicant.major, applicant.platforms,
                applicant.resume, applicant.website]
        ]}
    };

    let res = await gsapi.spreadsheets.values.append(appendOptions);
}